# config/mapper_params_online_async.yaml

use_sim_time: false  # Gunakan true jika menggunakan simulasi Gazebo

slam_toolbox:
  ros__parameters:
    use_sim_time: false
    yaml_filename: ""
    publish_period_sec: 0.05
    resolution: 0.05
    max_laser_range: 10.0
    minimum_time_interval: 0.5
    transform_publish_period: 0.05
    map_update_interval: 2.0
    scan_topic: scan
    mode: mapping
    debug_logging: false
    throttle_scans: 1
    tf_buffer_duration: 30.0
    enable_interactive_mode: false
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.017
    scan_match_resolution: 0.01
    use_orientation_filter: true
    map_frame: map
    odom_frame: odom
    base_frame: base_footprint
    global_frame: map
    odom_topic: odom
